from __future__ import annotations

from datetime import datetime, timedelta

from .auth import hash_password


def build_seed_state() -> dict:
    now = datetime.utcnow()

    maps = [
        {
            "id": 1,
            "name": "Mirage",
            "slug": "mirage",
            "overview": "中路控制和窗口烟是核心。适合用多段道具把 B 小和 A 连接切碎。",
            "cover_url": "/static/assets/maps/mirage-card.svg",
            "layout_url": "/static/assets/maps/mirage-layout.svg",
            "callout_color": "#ff7a18",
            "order": 1,
            "status": "published",
            "active_pool": True,
        },
        {
            "id": 2,
            "name": "Inferno",
            "slug": "inferno",
            "overview": "香蕉道节奏和二楼前压应对决定大部分回合走势。",
            "cover_url": "/static/assets/maps/inferno-card.svg",
            "layout_url": "/static/assets/maps/inferno-layout.svg",
            "callout_color": "#ffc145",
            "order": 2,
            "status": "published",
            "active_pool": True,
        },
        {
            "id": 3,
            "name": "Nuke",
            "slug": "nuke",
            "overview": "外场切线和黄房协同是 T 方拉开空间的前提。",
            "cover_url": "/static/assets/maps/nuke-card.svg",
            "layout_url": "/static/assets/maps/nuke-layout.svg",
            "callout_color": "#65d6ce",
            "order": 3,
            "status": "published",
            "active_pool": True,
        },
    ]

    points = [
        {"id": 1, "map_id": 1, "name": "T Spawn", "key": "mirage-t", "x": 10, "y": 82, "side": "T", "point_type": "staging", "tags": ["出生点"]},
        {"id": 2, "map_id": 1, "name": "A Ramp", "key": "mirage-ramp", "x": 28, "y": 64, "side": "T", "point_type": "staging", "tags": ["A 默认"]},
        {"id": 3, "map_id": 1, "name": "Window", "key": "mirage-window", "x": 47, "y": 37, "side": "CT", "point_type": "aim", "tags": ["中路"]},
        {"id": 4, "map_id": 1, "name": "Connector", "key": "mirage-connector", "x": 58, "y": 49, "side": "CT", "point_type": "utility", "tags": ["中控"]},
        {"id": 5, "map_id": 1, "name": "A Site", "key": "mirage-a", "x": 78, "y": 41, "side": "BOTH", "point_type": "site", "tags": ["爆弹"]},
        {"id": 6, "map_id": 2, "name": "T Ramp", "key": "inferno-t", "x": 9, "y": 77, "side": "T", "point_type": "staging", "tags": ["出生点"]},
        {"id": 7, "map_id": 2, "name": "Banana Logs", "key": "inferno-logs", "x": 34, "y": 41, "side": "T", "point_type": "staging", "tags": ["香蕉道"]},
        {"id": 8, "map_id": 2, "name": "CT Coffin", "key": "inferno-coffin", "x": 77, "y": 29, "side": "CT", "point_type": "aim", "tags": ["B 点"]},
        {"id": 9, "map_id": 2, "name": "B Site", "key": "inferno-b", "x": 83, "y": 32, "side": "BOTH", "point_type": "site", "tags": ["爆弹"]},
        {"id": 10, "map_id": 3, "name": "T Red Box", "key": "nuke-red", "x": 20, "y": 72, "side": "T", "point_type": "staging", "tags": ["外场"]},
        {"id": 11, "map_id": 3, "name": "Garage Roof", "key": "nuke-garage", "x": 46, "y": 28, "side": "CT", "point_type": "aim", "tags": ["外场"]},
        {"id": 12, "map_id": 3, "name": "Secret", "key": "nuke-secret", "x": 67, "y": 65, "side": "BOTH", "point_type": "utility", "tags": ["地下"]},
    ]

    lineups = [
        {
            "id": 1,
            "map_id": 1,
            "title": "Mirage 窗口烟",
            "slug": "mirage-window-smoke",
            "side": "T",
            "utility_type": "smoke",
            "start_point_id": 1,
            "aim_point_id": 3,
            "land_point_id": 3,
            "purpose": "切掉窗口信息，方便中路过点和 connector 控制。",
            "difficulty": "easy",
            "summary": "经典中路窗口烟，适合默认开局和中控展开。",
            "steps": ["出生点贴左墙站定", "准星对准屋檐阴影边角", "起跳同时左键投掷"],
            "media": ["/static/assets/maps/mirage-lineup-window.svg"],
            "status": "published",
        },
        {
            "id": 2,
            "map_id": 1,
            "title": "Mirage 连接烟",
            "slug": "mirage-connector-smoke",
            "side": "T",
            "utility_type": "smoke",
            "start_point_id": 2,
            "aim_point_id": 4,
            "land_point_id": 4,
            "purpose": "切断 A 连接回防，保护爆弹推进。",
            "difficulty": "medium",
            "summary": "A 坡默认集合后丢的连接烟，适合双烟 A 爆。",
            "steps": ["A 坡左侧木箱靠住", "瞄准连接上方天线", "原地左键投掷"],
            "media": ["/static/assets/maps/mirage-lineup-connector.svg"],
            "status": "published",
        },
        {
            "id": 3,
            "map_id": 2,
            "title": "Inferno 棺材火",
            "slug": "inferno-coffin-molotov",
            "side": "T",
            "utility_type": "molotov",
            "start_point_id": 7,
            "aim_point_id": 8,
            "land_point_id": 8,
            "purpose": "清理棺材死角，迫使 B 点 CT 交位。",
            "difficulty": "easy",
            "summary": "香蕉道默认道具，适合 B 爆和二次展开。",
            "steps": ["木头位站定", "准星压在棺材上沿", "跑两步后左键投掷"],
            "media": ["/static/assets/maps/inferno-lineup-coffin.svg"],
            "status": "published",
        },
        {
            "id": 4,
            "map_id": 3,
            "title": "Nuke 外场切线烟",
            "slug": "nuke-secret-wall-smoke",
            "side": "T",
            "utility_type": "smoke",
            "start_point_id": 10,
            "aim_point_id": 11,
            "land_point_id": 12,
            "purpose": "建立外场烟墙，安全下 secret。",
            "difficulty": "hard",
            "summary": "外场一线烟核心线路，适合标准外场展开。",
            "steps": ["红箱边缘对齐", "对准车库屋顶分界", "跳投完成切线"],
            "media": ["/static/assets/maps/nuke-lineup-secret.svg"],
            "status": "published",
        },
    ]

    tactics = [
        {
            "id": 1,
            "map_id": 1,
            "title": "Mirage A 爆双烟闪同步",
            "slug": "mirage-a-exec-double-smoke",
            "side": "T",
            "goal": "A 点爆弹",
            "phase": "exec",
            "difficulty": "medium",
            "players": 4,
            "summary": "窗口烟和连接烟同步落地，配合过点闪一波吃掉 A 点防守。",
            "note": "如果 CT 在 VIP 提前前顶，需要一名中路队员补一颗补位闪。",
            "tags": ["A爆", "双烟", "同步"],
            "cover_url": "/static/assets/maps/mirage-card.svg",
            "status": "published",
            "featured": True,
            "created_at": (now - timedelta(days=2)).isoformat(),
            "routes": [],
            "step_items": [
                {"order": 1, "role": "辅助位", "type": "utility", "instruction": "先给窗口烟，确保中路狙击位失去信息。", "lineup_id": 1},
                {"order": 2, "role": "二道具位", "type": "utility", "instruction": "A 坡补连接烟，压缩 CT 回防路线。", "lineup_id": 2},
                {"order": 3, "role": "主突破", "type": "move", "instruction": "等双烟落地后贴墙出 A 坡，吃过点闪。", "lineup_id": None},
                {"order": 4, "role": "补枪位", "type": "trade", "instruction": "跟进默认箱和 ticket 方向补枪。", "lineup_id": None},
            ],
        },
        {
            "id": 2,
            "map_id": 2,
            "title": "Inferno B 爆棺材火节奏",
            "slug": "inferno-b-hit-coffin-molly",
            "side": "T",
            "goal": "B 点爆弹",
            "phase": "exec",
            "difficulty": "easy",
            "players": 3,
            "summary": "用棺材火把 B 点守位顶出来，再用人海速度抢包点。",
            "note": "如果 CT 反清香蕉道失败，保留一颗灭火烟能明显提高容错。",
            "tags": ["B爆", "火攻", "香蕉道"],
            "cover_url": "/static/assets/maps/inferno-card.svg",
            "status": "published",
            "featured": True,
            "created_at": (now - timedelta(days=5)).isoformat(),
            "step_items": [
                {"order": 1, "role": "道具位", "type": "utility", "instruction": "先给棺材火，强制包点内 CT 转位。", "lineup_id": 3},
                {"order": 2, "role": "主突破", "type": "move", "instruction": "火焰扩散后立刻贴右墙冲 B。", "lineup_id": None},
                {"order": 3, "role": "二突破", "type": "hold", "instruction": "优先看三箱和喷泉反打。", "lineup_id": None},
            ],
        },
        {
            "id": 3,
            "map_id": 3,
            "title": "Nuke 外场一线烟下 secret",
            "slug": "nuke-secret-walkthrough",
            "side": "T",
            "goal": "外场转地下",
            "phase": "default",
            "difficulty": "hard",
            "players": 4,
            "summary": "靠外场切线拿到地下控制，再衔接 B 点或回转上层包夹。",
            "note": "如果对手前压黄房，先拿黄房控制再出烟。",
            "tags": ["外场", "地下", "默认"],
            "cover_url": "/static/assets/maps/nuke-card.svg",
            "status": "published",
            "featured": False,
            "created_at": (now - timedelta(days=1)).isoformat(),
            "step_items": [
                {"order": 1, "role": "烟位", "type": "utility", "instruction": "完成外场切线烟，遮蔽主视野。", "lineup_id": 4},
                {"order": 2, "role": "侦查位", "type": "move", "instruction": "贴红箱观察近点，没有近点再下 secret。", "lineup_id": None},
                {"order": 3, "role": "补枪位", "type": "trade", "instruction": "第二身位沿烟边补枪，防止 CT 穿烟前压。", "lineup_id": None},
            ],
        },
    ]

    users = [
        {
            "id": 1,
            "username": "demo",
            "email": "demo@cs2tactics.local",
            "password_hash": hash_password("demo123"),
            "role": "player",
            "favorite_ids": [1],
            "recent_tactic_ids": [3, 1],
        },
        {
            "id": 2,
            "username": "admin",
            "email": "admin@cs2tactics.local",
            "password_hash": hash_password("admin123"),
            "role": "admin",
            "favorite_ids": [],
            "recent_tactic_ids": [],
        },
    ]

    return {
        "maps": maps,
        "points": points,
        "lineups": lineups,
        "tactics": tactics,
        "users": users,
        "assets": [],
        "counters": {
            "maps": len(maps) + 1,
            "points": len(points) + 1,
            "lineups": len(lineups) + 1,
            "tactics": len(tactics) + 1,
            "users": len(users) + 1,
            "assets": 1,
        },
    }
